[package]
name = "actix-bililive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
awc = { version = "3.0.0-beta.9", features = ["openssl"] }
actix-codec = "0.4"
bililive-core = { path = "../bililive-core", features = ["tokio"] }
serde = "1.0"

[dev-dependencies]
actix-rt = "2.3"